### ISSUE TITLE
nms_cuda.c not found

### ISSUE THREAD

**Issue by monkeyshichi** [zhengye1995/DCIC19-Rebar-detection-Rank2#1]
when Compiling nms kernels by nvcc,
/DCIC19-Rebar-detection-Rank2-master/lib/model/nms/src/nms_cuda.c: No such file or directory

**Comment by monkeyshichi** [comment]
请大神赐教！

**Comment by zhengye1995** [comment]
Sorry, I missed this file and I upload it now.

**Comment by monkeyshichi** [comment]
Thanks, when i run program,it go wrong. the message is : cuda error:out of memory ,i only have 4G gpu memory ,do you have method to solve this problem ?For example, change some parameters.

**Comment by zhengye1995** [comment]
Because this code is based on detectron, wich is a old version for detectron, now detectron has a new version for detectron2, and you can try it. In detectron1,  it needs huge GPU memory for training and testing. If you just has a GPU with 4GB memory, I suggest you try to decrease the image size of input and use a light backbone like resnet50, but maybe it still not enough.  Finally, I suggest  you try detectron2 or mmdetection and other new object detection tools, detectron is so old now.

**Comment by monkeyshichi** [comment]
i trained with one image per batch .i will try detectron2 or mmdetection.Thanks a lot.
